taskmanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo_list.urls', namespace='todo')),
]

todo_list/urls.py
from django.urls import path
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskDelete, CustomLoginView, RegisterPage
from django.contrib.auth.views import LogoutView

app_name = 'todo'

urlpatterns = [
    path('list/', TaskList.as_view(), name='list'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='detail'),
    path('task/create/', TaskCreate.as_view(), name='create'),
    path('task/edit/<int:pk>/', TaskUpdate.as_view(), name='edit'),
    path('task/delete/<int:pk>/', TaskDelete.as_view(), name='delete'),

    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='todo:login'), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),

]

todo_list/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['complete']

todo_list/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

from django.urls import reverse_lazy

from .models import Task


# Create your views here.

class CustomLoginView(LoginView):
    template_name = 'todo_list/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('todo:list')


class RegisterPage(FormView):
    template_name = 'todo_list/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('todo:login')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('todo:list')
        return super(RegisterPage, self).get(*args, **kwargs)


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()
        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(
                title__icontains=search_input)
        context['search_input'] = search_input
        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'todo_list/task.html'


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('todo:list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('todo:list')


class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('todo:list')

todo_list/templates/todo_list/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>To Do</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&family=Raleway:wght@100;200&family=Rubik+Pixels&display=swap" rel="stylesheet">

    <style>
        body{
            background-color: #FAFAFA;
            font-family: 'Nunito', sans-serif;
            padding-top:50px;
        }

        h1,h2,h3,h4,h5,h6{
            font-family: 'Raleway', sans-serif;
        }

        a,p{
            color:#4b5156;
        }

        .container{
        max-width:550px;
        margin:auto;
        background-color:#fff;
        -webkit-box-shadow: 2px 2px 13px -4px rgba(0,0,0,0.21);
        box-shadow: 2px 2px 13px -4px rgba(0,0,0,0.21);
        }

        .header-bar{
            display: flex;
            justify-content: space-between;
            color: #fff;
            padding:10px;
            border-radius: 5px 5px 0 0;
            background: linear-gradient(90deg, #EEA390 0%, #EB796F 43%, #EB796F 100%);
        }

        .header-bar a{
            color: rgb(247, 247, 247);
            text-decoration: none;
        }

        .task-wrapper{
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 20px;
            background-color: #fff;
            border-top:1px solid rgb(226, 226, 226);
        }

        .task-title {
            display: flex;
        }

        .task-title a {
            text-decoration: none;
            color: #4b5156;
            margin-left: 10px;
        }

        .task-complete-icon{
            height: 20px;
            width: 20px;
            background-color: rgb(105, 192, 105);
            border-radius: 50%;
        }

        .task-incomplete-icon{
            height: 20px;
            width: 20px;
            background-color: rgb(218, 218, 218);
            border-radius:50%;
        }

        .delete-link{
            text-decoration: none;
            font-weight: 900;
            color: #cf4949;
            font-size: 22px;
            line-height: 0;
        }

        #search-add-wrapper{
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
        }

        #add-link{
            color:#EB796F;
            text-decoration:none;
            font-size: 42px;
            text-shadow: 1px 1px #81413b;
        }

        input[type=text], input[type=password], textarea{
            border: 1px solid #EB796F;
            border-radius: 5px;
            padding: 10px;
            width: 90%;
        }

        .label{
            padding-top: 10px !important;
            display: block;
        }

        .button{
            border:1px solid #EB796F;
            background-color: #FAFAFA;
            color: #EB796F;
            padding: 10px;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }

        .card-body{
            padding: 20px;
        }
    </style>
</head>
<body>

    <div class = 'container'>
        {% block content%}
        {% endblock content%}
    </div>

</body>
</html>

todo_list/templates/todo_list/login.html
{% extends 'todo_list/base.html' %}
{% block content %}

<div class="header-bar">
    <h1>Login</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Login">
    </form>
    <p>Do not have an account? <a href="{% url 'todo:register' %}">Register</a></p>
</div>

{% endblock content %}

todo_list/templates/todo_list/register.html
{% extends 'todo_list/base.html' %}
{% block content %}

<div class="header-bar">
    <h1>Register</h1>
</div>

<div class="card-body">
    <form method="POST">
    {% csrf_token %}
    <label for="">{{form.username.label}}</label>
    {{form.username}}

    <label for="">{{form.password1.label}}</label>
    {{form.password1}}

    <label for="">{{form.password2.label}}</label>
    {{form.password2}}

    <input style="margin-top:10px;" class="button" type="submit" value="Register">
    </form>

    <p>Already have an account? <a href="{% url 'todo:login' %}">Login</a></p>
</div>


{% endblock content %}

todo_list/templates/todo_list/task.html
{% extends 'todo_list/base.html' %}
{% block content %}

<h1> Task: {{task.title}}</h1>
<p>Description:{{task.description}}</p>
{% endblock content %}

todo_list/templates/todo_list/task_confirm_delete.html
{% extends 'todo_list/base.html' %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'todo:list' %}">&#8592 Go Back</a>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete this task? "{{task}}"</p>
        <input class="button" type="submit" value="Delete">
    </form>
</div>


{% endblock content %}

todo_list/templates/todo_list/task_form.html
{% extends 'todo_list/base.html' %}
{% block content %}


<div class="header-bar">
    <a href="{% url 'todo:list' %}">&#8592 Back</a>
</div>

<div class="card-body">
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Submit">
    </form>
</div>


{% endblock content %}

todo_list/templates/todo_list/task_list.html
{% extends 'todo_list/base.html' %}
{% block content %}

<div class="header-bar">
    <div>
        <h1>Hello {{request.user|title}}</h1>
        <h3 style="margin:0"> You have <i>{{count}}</i> incomplete task{{ count|pluralize:"s"}}</h3>
    </div>

    {% if request.user.is_authenticated %}
    <a href="{% url 'todo:logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'todo:login' %}">Login</a>
    {% endif %}

</div>


<div id="search-add-wrapper">
    <form method="GET" style="margin-top: 20px; display: flex;">
        <input type="text" name="search-area" value="{{search_input}}">
        <input class="button" type="submit" value="Search">
    </form>
    <a id="add-link" href="{% url 'todo:create' %}">&#x2b;</a>
</div>





<div class="task-items-wrapper">
    {% for task in tasks %}
        <div class="task-wrapper">
            {% if task.complete %}
                <div class="task-title">
                    <div class="task-complete-icon"></div>
                        <i><s><a href="{% url 'todo:edit' task.id %}">{{task}}</a></s></i>
                </div>
            <a class="delete-link" href="{% url 'todo:delete' task.id %}">&#215;</a>
            {% else %}
                <div class="task-title">
                    <div class="task-incomplete-icon"></div>
                        <a href="{% url 'todo:edit' task.id %}">{{task}}</a>
                </div>
            <a class="delete-link" href="{% url 'todo:delete' task.id %}">&#215;</a>
            {% endif %}

        </div>
    {% empty %}
    <h3>No items in list</h3>
    {% endfor %}
</div>
{% endblock content %}